---
apiVersion: v1
data:
  api-token: dHFVX0FjZ1FFQzRWVTNHaHA4c3lDOUNRRFJnZUVVdl80bGRpS3prXw==
kind: Secret
metadata:
  name: cloudflare-api-token-secret
type: Opaque
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-traefik
spec:
  commonName: traefik.adadeeeh.com
  secretName: wild
  dnsNames:
    - "*.staging.armis.tech"
    - "staging.armis.tech"
  issuerRef:
    kind: Issuer
    name: letsencrypt-staging
---