---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: error
spec:
  replicas: 1
  selector:
    matchLabels:
      app: error
  template:
    metadata:
      labels:
        app: error
    spec:
      containers:
        - image: valentin208/error:0.1
          imagePullPolicy: Always
          name: error
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 500Mi
          ports:
            - containerPort: 80
              name: error
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: error
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
  selector:
    app: error